#!/bin/bash

XPI=voz-living-mobile.xpi

# Replace this value to push to different release channels.
# Nightly = org.mozilla.fennec
# Aurora = org.mozilla.fennec_aurora
# Beta = org.mozilla.firefox_beta
# Release = org.mozilla.firefox
ANDROID_APP_ID=org.mozilla.firefox

# List add-on files here
zip -r $XPI bootstrap.js \
            install.rdf \
            chrome.manifest \
            content \
            locale \
            README.md \
            index.js \
            package.json \
            data/vozforums-responsive.css \
            data/vozforums-content.js \
    -x *.DS_Store*

# Push the add-on to your device to test
adb push "$XPI" /sdcard/"$XPI" && \

# Push an HTML page to link to add-on
adb push install.html /sdcard/install.html && \

adb shell am start -a android.intent.action.VIEW \
                   -c android.intent.category.DEFAULT \
                   -d file:///mnt/sdcard/install.html \
                   -n $ANDROID_APP_ID/.App && \
echo Pushed $XPI to $ANDROID_APP_ID
